/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AttractionCard: typeof import('./components/attraction/AttractionCard.vue')['default']
    AttractionListCard: typeof import('./components/attraction/AttractionListCard.vue')['default']
    AuthDrawer: typeof import('./components/auth/AuthDrawer.vue')['default']
    CuratedDestinations: typeof import('./components/home/CuratedDestinations.vue')['default']
    DiaryCollectionState: typeof import('./components/diaries/DiaryCollectionState.vue')['default']
    DiaryCommentSection: typeof import('./components/diaries/DiaryCommentSection.vue')['default']
    DiaryEditorialCard: typeof import('./components/diaries/DiaryEditorialCard.vue')['default']
    DiaryInteractionPanel: typeof import('./components/diaries/DiaryInteractionPanel.vue')['default']
    DiaryMagazinePagination: typeof import('./components/diaries/DiaryMagazinePagination.vue')['default']
    DiaryRichContent: typeof import('./components/diaries/DiaryRichContent.vue')['default']
    DiaryShelfCard: typeof import('./components/diaries/DiaryShelfCard.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    GlobalInsight: typeof import('./components/home/GlobalInsight.vue')['default']
    HomeHero: typeof import('./components/home/HomeHero.vue')['default']
    ImageUploadCard: typeof import('./components/user/ImageUploadCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheFooter: typeof import('./components/layout/TheFooter.vue')['default']
    TheHeader: typeof import('./components/layout/TheHeader.vue')['default']
    TravelerDiaries: typeof import('./components/home/TravelerDiaries.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
